name = "mvp-versao-6-0"
main = "index.js"
compatibility_date = "2026-09-16"

[vars]
GEMINI_MODEL = "gemini-3.8-flash"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "lidire-mvp-db"
database_id = "1a095fd7-b0a0-4b83-b610-1b3a43fbb716"
